
export const ADD_MARKER = 'MARKERS_ADDED';
export const CLEAR_MARKERS = 'CLEAR_MARKERS';
export const SET_ACTIVE_MARKER = 'SET_ACTIVE_MARKER';
export const SET_ACTIVE_MARKER2 = 'SET_ACTIVE_MARKER2';

export const SET_DISTANSE_TO_MARKER = 'SET_DISTANCE_TO_MARKER';
